### ISSUE TITLE
Why backup one column is needed?

### ISSUE THREAD

**Issue by budimanjojo** [taybart/b64.nvim#1]
Hello, thanks for this plugin. I just tried this and noticed that it deleted one column to the left.
https://github.com/taybart/b64.nvim/blob/b18a79c287b581f1801a631bc5f69404f9f8aed4/lua/b64.lua#L31

My usecase is to decrypt a kubernetes `Secret` resource. which is like this:
```
apiVersion: v1
kind: Secret
metadata:
  name: a-secret
data:
  key: <base64-encoded-string>
```
when I try to decode that value, it become like this: `key:<decoded-string>`
